SistemaCadenaAlimenticia.Web/Models/ErrorViewModel.cs
namespace SistemaCadenaAlimenticia.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SistemaCadenaAlimenticia.Web/Controllers/CadenaAlimenticiaController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaCadenaAlimenticia.Data.EF;
using SistemaCadenaAlimenticia.Servicios;

namespace SistemaCadenaAlimenticia.Web.Controllers
{
    public class CadenaAlimenticiaController : Controller
    {
        private readonly ICadenaAlimenticiaServicio _servicio;
        public CadenaAlimenticiaController(ICadenaAlimenticiaServicio servicio) {
        
            _servicio = servicio;
        }
        public IActionResult Index()
        {
           ViewBag.Sucursales = _servicio.GetSucursals();
            return View();
        }
        public IActionResult Sucursales(int IdCadena)
        {
            ViewBag.Cadenas = _servicio.GetCadenas();
            if (IdCadena  < 0)
            {
                return Redirect("/CadenaAlimenticia/Sucursales");
            }
            var sucursalesFiltradas=  _servicio.FiltrarSucursales(IdCadena);
            return View(sucursalesFiltradas);
        }
        [HttpGet]
        public IActionResult AltaSucursal()
        {
            var cadenas = _servicio.GetCadenas();
            return View(cadenas);
        }
        [HttpPost]
        public IActionResult AltaSucursal(Sucursal sucursal)
        {
            if (sucursal != null)
             _servicio.AltaSucursal(sucursal);
            TempData["Exito"] = "Se ha registrado exitosamente";
            return Redirect("/CadenaAlimenticia/Index");

        }

    }
}

SistemaCadenaAlimenticia.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaCadenaAlimenticia.Web.Models;
using System.Diagnostics;

namespace SistemaCadenaAlimenticia.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaCadenaAlimenticia.Web/Views/CadenaAlimenticia/AltaSucursal.cshtml
@model List<SistemaCadenaAlimenticia.Data.EF.Cadena>;

<h1>Agregue una nueva sucursal</h1>
<div>
    <form action="/CadenaAlimenticia/AltaSucursal" method="post">
        <input type="hidden" name="IdSucursal"/>
        <div class="mb-3">
            <select name="IdCadena">
                @foreach (var cadena in Model)
                {
                    <option value="@cadena.IdCadena">@cadena.RazonSocial</option>
                }
            </select>
        </div>

        <div class ="mb-3">
            Direccion: <input type="text" name="Direccion" />
        </div>
        <div class="mb-3">
            Ciudad: <input type="text" name="Ciudad" />
        </div>
        <div>
            <input type="submit" value="Guardar"/>
        </div>
    </form>
</div>

SistemaCadenaAlimenticia.Web/Views/CadenaAlimenticia/Index.cshtml
@using SistemaCadenaAlimenticia.Data.EF
<div class="alert-success mt-3">
    @TempData["Exito"]
</div>
<div>
    <h1 class="text-center">Sucursales</h1>
    <table class="table">
        <tr>
            <th>Id </th>
            <th>Direccion</th>
            <th>Ciudad</th>
            <th>Cadena</th>
        </tr>
        @foreach (var sucursal in ViewBag.Sucursales)
        {
            <tr>
                <td>@sucursal.IdSucursal</td>
                <td>@sucursal.Direccion</td>
                <td>@sucursal.Ciudad</td>
                <td>@sucursal.IdCadenaNavigation.RazonSocial</td>
            </tr>
        }
    </table>
</div>

SistemaCadenaAlimenticia.Web/Views/CadenaAlimenticia/Sucursales.cshtml
@using SistemaCadenaAlimenticia.Data.EF
@model List<Sucursal>
<h1>Bienvenido</h1>
<h2>Para buscar sucursales, elija una de las siguientes cadenas</h2>

<div class="d-flex">
    <form action="/CadenaAlimenticia/Sucursales" method="post">
        <div>
            <select name="IdCadena">
                @foreach (var cadena in ViewBag.Cadenas)
                {
                    <option  value="@cadena.IdCadena">@cadena.RazonSocial</option>
                }
            </select>
            <input class="btn btn-secondary" type="submit" value="Filtrar" />
        </div>
    </form>
</div>
<div>
    @if(Model.Count >0){
    <h1 class="text-center">Sucursales</h1>
    <table class="table">
        <tr>
            <th>Id Sucursal</th>
            <th>Direccion</th>
            <th>Ciudad</th>
            <th>Cadena</th>

        </tr>
        @foreach (var sucursal in Model)
        {
            <tr>
                <td>@sucursal.IdSucursal</td>
                <td>@sucursal.Direccion</td>
                <td>@sucursal.Ciudad</td>
                <td>@sucursal.IdCadenaNavigation.RazonSocial</td>

            </tr>
        }
    </table>
    }
</div>

SistemaCadenaAlimenticia.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SistemaCadenaAlimenticia.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaCadenaAlimenticia.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaCadenaAlimenticia.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemaCadenaAlimenticia.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CadenaAlimenticia" asp-action="Sucursales">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CadenaAlimenticia" asp-action="Index">Todas las sucursales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CadenaAlimenticia" asp-action="AltaSucursal">Agregar sucursal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SistemaCadenaAlimenticia.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>